# Generated by Django 5.1.3 on 2025-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("student_id", models.CharField(max_length=20, verbose_name="学生ID")),
                ("uwb_id", models.CharField(max_length=20, verbose_name="UWB定位标签id")),
                ("seat_x", models.FloatField(default=0.0, verbose_name="座位横坐标")),
                ("seat_y", models.FloatField(default=0.0, verbose_name="座位纵坐标")),
            ],
        ),
    ]
