# Generated by Django 5.1.3 on 2025-07-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
        migrations.AddField(
            model_name="student",
            name="speciality",
            field=models.CharField(default="无", max_length=100, verbose_name="特殊需求"),
        ),
    ]
