# Generated by Django 5.1.3 on 2025-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0002_student_age_student_speciality"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformationMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrix", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
