# Generated by Django 5.1.3 on 2025-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0003_transformationmatrix"),
    ]

    operations = [
        migrations.CreateModel(
            name="Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("run", models.IntegerField(default=0, verbose_name="跑动")),
                ("stand", models.IntegerField(default=0, verbose_name="站立")),
                ("lookAround", models.IntegerField(default=0, verbose_name="东张西望")),
                ("offSeat", models.IntegerField(default=0, verbose_name="离座")),
                ("sleeping", models.IntegerField(default=0, verbose_name="瞌睡")),
                ("handup", models.IntegerField(default=0, verbose_name="举手")),
                ("standup", models.IntegerField(default=0, verbose_name="起立")),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrix", models.JSONField(verbose_name="单应性矩阵")),
                ("baseA_x", models.FloatField(default=0, verbose_name="A基站x坐标")),
                ("baseA_y", models.FloatField(default=0, verbose_name="A基站y坐标")),
                ("baseB_x", models.FloatField(default=0, verbose_name="B基站x坐标")),
                ("baseB_y", models.FloatField(default=0, verbose_name="B基站y坐标")),
                ("baseC_x", models.FloatField(default=0, verbose_name="C基站x坐标")),
                ("baseC_y", models.FloatField(default=0, verbose_name="C基站y坐标")),
                ("ptz_x", models.FloatField(default=0, verbose_name="云台x坐标")),
                ("ptz_y", models.FloatField(default=0, verbose_name="云台y坐标")),
            ],
        ),
        migrations.DeleteModel(
            name="TransformationMatrix",
        ),
    ]
