# Generated by Django 5.1.3 on 2025-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0004_behavior_classroom_delete_transformationmatrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="matrix",
            field=models.JSONField(default=None, verbose_name="单应性矩阵"),
        ),
    ]
