# Generated by Django 5.1.3 on 2025-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0005_alter_classroom_matrix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behavior",
            name="stand",
        ),
        migrations.AddField(
            model_name="behavior",
            name="walk",
            field=models.IntegerField(default=0, verbose_name="走动"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="class_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
