# Generated by Django 5.1.3 on 2025-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0006_remove_behavior_stand_behavior_walk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="matrix",
            field=models.JSONField(default=None, null=True, verbose_name="单应性矩阵"),
        ),
    ]
