# Generated by Django 5.1.3 on 2025-07-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0007_alter_classroom_matrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="base_z",
            field=models.FloatField(default=0, verbose_name="基站共同z坐标"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="ptz_z",
            field=models.FloatField(default=0, verbose_name="云台z坐标"),
        ),
    ]
