# Generated by Django 5.1.3 on 2025-07-20 12:26

import camera.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0008_classroom_base_z_classroom_ptz_z"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default.png",
                        null=True,
                        upload_to=camera.models.user_avatar_path,
                        verbose_name="头像",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentStudentBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=100, verbose_name="学生学号")),
                (
                    "student_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="学生姓名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_bindings",
                        to="camera.user",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
