# Generated by Django 5.2.4 on 2025-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_user_parentstudentbinding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavior',
            old_name='handup',
            new_name='hand_up',
        ),
        migrations.RenameField(
            model_name='behavior',
            old_name='lookAround',
            new_name='look_around',
        ),
        migrations.RenameField(
            model_name='behavior',
            old_name='offSeat',
            new_name='off_seat',
        ),
        migrations.RenameField(
            model_name='behavior',
            old_name='standup',
            new_name='stand_up',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='run',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='walk',
        ),
        migrations.AddField(
            model_name='behavior',
            name='hyperactive',
            field=models.IntegerField(default=0, verbose_name='多动'),
        ),
    ]
