# Generated by Django 5.2.4 on 2025-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_rename_handup_behavior_hand_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='focus_time',
            field=models.FloatField(default=0, verbose_name='专注时长'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='subject',
            field=models.CharField(default='语文', max_length=100, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
