# Generated by Django 5.1.3 on 2025-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0011_behavior_focus_time_behavior_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavior",
            name="focus_time",
            field=models.FloatField(default=0, verbose_name="专注时长(分钟)"),
        ),
    ]
