# Generated by Django 5.2.4 on 2025-08-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_behavior_focus_time_behavior_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='camera.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='focus_time',
            field=models.FloatField(default=0, verbose_name='专注时长(分钟)'),
        ),
    ]
