# Generated by Django 5.1.3 on 2025-08-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0012_alter_behavior_focus_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户管理"},
        ),
        migrations.AddField(
            model_name="behavior",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="camera.student",
                verbose_name="学生",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$AQEmdKkOPZnOuDfeSjTMC9$cR+BBiBMyXf/OLVU+bs1i5/nkw0TxWW5bV02v3Moyg8=",
                max_length=128,
                verbose_name="password",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user", max_length=150, unique=True, verbose_name="用户名"
            ),
        ),
    ]
