# Generated by Django 5.2.4 on 2025-08-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_behavior_student_alter_behavior_focus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='camera.student', verbose_name='学生'),
        ),
    ]
