# Generated by Django 5.1.3 on 2025-08-11 08:46

import camera.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0013_alter_user_options_behavior_student_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_id",
            field=models.CharField(default="001", max_length=100, verbose_name="班级号"),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=10, null=True, verbose_name="性别"),
        ),
        migrations.AddField(
            model_name="user",
            name="class_id",
            field=models.CharField(default="001", max_length=100, verbose_name="班级号"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/img/pig.png",
                null=True,
                upload_to=camera.models.user_avatar_path,
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$QBbllDTtYEfGYTAcO5L3Jg$l6C6TpEUcAWBk7NX8LIbPheWdHC6hhMK8JJ/R3XZhaI=",
                max_length=128,
                verbose_name="password",
            ),
        ),
    ]
