# Generated by Django 5.2.4 on 2025-08-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$pvpKs4KlP8x16IkIc5vQRF$MzQn1NWvD9O0r0vyZtucoNajUjsNJ92cnWNE4i8bYC4=', max_length=128, verbose_name='password'),
        ),
    ]
