# Generated by Django 5.2.4 on 2025-08-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$ZjUw4oKUebYiWZJvh2hYkD$stc0jvkQRPCfw3PuZiWwwjTmOofHwE8qEgZS4mdNAdo=', max_length=128, verbose_name='password'),
        ),
    ]
