# Generated by Django 5.2.4 on 2025-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$URcB7RRHCHtBq5UKYsJA5r$L/mnmIUGcOXiQ2N6EqMnQeMhfTiXzSmskSTjZz8c/rk=', max_length=128, verbose_name='password'),
        ),
    ]
